`timescale 1ns / 1ps

module total_tb;

    localparam integer CLK_PERIOD = 20;       // 50 MHz
    localparam integer CLK_FREQ   = 50000000;
    localparam integer TB_BAUD    = 1000000;  // speed up UART simulation
    localparam integer CHECK_NUM  = 256;
    localparam integer UART_BYTES = CHECK_NUM * 2;
    localparam integer BAUD_CLKS  = CLK_FREQ / TB_BAUD;

    reg clk;
    reg rst_n;
    reg uart_rx;
    reg key0;
    reg key1;
    reg adc_dout;

    wire adc_cs;
    wire adc_sclk;
    wire adc_din;
    wire uart_tx;

    integer i;
    integer write_cnt;
    integer tx_cnt;
    integer error_cnt;
    integer adc_sample_idx;
    reg [15:0] exp_data;
    reg [7:0]  rx_byte;
    reg [3:0]  adc_bit_sel;
    reg [11:0] adc_model_data;

    total dut (
        .clk      (clk),
        .rst_n    (rst_n),
        .uart_rx  (uart_rx),
        .key0     (key0),
        .key1     (key1),
        .adc_dout (adc_dout),
        .adc_cs   (adc_cs),
        .adc_sclk (adc_sclk),
        .adc_din  (adc_din),
        .uart_tx  (uart_tx)
    );

    defparam dut.uart_rx_inst.BAUD_RATE = TB_BAUD;
    defparam dut.uart_tx_inst.BAUD_RATE = TB_BAUD;
    defparam dut.key1_inst.CNT_MAX      = 20;

    initial begin
        clk = 1'b0;
        forever #(CLK_PERIOD / 2) clk = ~clk;
    end

    function [11:0] adc_raw_sample;
        input [31:0] idx;
        begin
            adc_raw_sample = 12'd1000 + idx[11:0];
        end
    endfunction

    function [15:0] adc_to_voltage;
        input [11:0] raw_data;
        reg [31:0] mult_data;
        begin
            mult_data = 52800 * raw_data;
            adc_to_voltage = mult_data >> 16;
        end
    endfunction

    always @(negedge adc_cs or negedge rst_n) begin
        if (!rst_n) begin
            adc_model_data <= adc_raw_sample(0);
        end else begin
            adc_model_data <= adc_raw_sample(adc_sample_idx);
        end
    end

    always @(negedge adc_sclk or posedge adc_cs or negedge rst_n) begin
        if (!rst_n) begin
            adc_dout <= 1'b0;
        end else if (adc_cs) begin
            adc_dout <= 1'b0;
        end else begin
            case (adc_bit_sel)
                4'd4:  adc_dout <= adc_model_data[11];
                4'd5:  adc_dout <= adc_model_data[10];
                4'd6:  adc_dout <= adc_model_data[9];
                4'd7:  adc_dout <= adc_model_data[8];
                4'd8:  adc_dout <= adc_model_data[7];
                4'd9:  adc_dout <= adc_model_data[6];
                4'd10: adc_dout <= adc_model_data[5];
                4'd11: adc_dout <= adc_model_data[4];
                4'd12: adc_dout <= adc_model_data[3];
                4'd13: adc_dout <= adc_model_data[2];
                4'd14: adc_dout <= adc_model_data[1];
                4'd15: adc_dout <= adc_model_data[0];
                default: adc_dout <= 1'b0;
            endcase
        end
    end

    always @(posedge adc_sclk or posedge adc_cs or negedge rst_n) begin
        if (!rst_n) begin
            adc_bit_sel <= 4'd0;
        end else if (adc_cs) begin
            adc_bit_sel <= 4'd0;
        end else begin
            adc_bit_sel <= adc_bit_sel + 1'b1;
        end
    end

    always @(posedge adc_cs or negedge rst_n) begin
        if (!rst_n) begin
            adc_sample_idx <= 0;
        end else if (adc_sample_idx < CHECK_NUM) begin
            adc_sample_idx <= adc_sample_idx + 1;
        end
    end

    task send_uart_byte;
        input [7:0] data;
        integer bit_idx;
        begin
            uart_rx = 1'b0;
            repeat (BAUD_CLKS) @(posedge clk);

            for (bit_idx = 0; bit_idx < 8; bit_idx = bit_idx + 1) begin
                uart_rx = data[bit_idx];
                repeat (BAUD_CLKS) @(posedge clk);
            end

            uart_rx = 1'b1;
            repeat (BAUD_CLKS) @(posedge clk);
        end
    endtask

    task press_key1;
        begin
            key1 = 1'b0;
            repeat (40) @(posedge clk);
            key1 = 1'b1;
            repeat (40) @(posedge clk);
        end
    endtask

    task recv_uart_byte;
        output [7:0] data;
        integer bit_idx;
        begin
            data = 8'd0;

            @(negedge uart_tx);
            repeat (BAUD_CLKS + (BAUD_CLKS / 2)) @(posedge clk);

            for (bit_idx = 0; bit_idx < 8; bit_idx = bit_idx + 1) begin
                data[bit_idx] = uart_tx;
                repeat (BAUD_CLKS) @(posedge clk);
            end

            if (uart_tx !== 1'b1) begin
                error_cnt = error_cnt + 1;
            end

            repeat (BAUD_CLKS / 2) @(posedge clk);
        end
    endtask

    // Count and check every RAM write generated by total.v.
    always @(posedge clk) begin
        if (rst_n && dut.ena && dut.wea) begin
            exp_data = adc_to_voltage(adc_raw_sample(write_cnt));

            if (dut.addra !== write_cnt[7:0]) begin
                error_cnt = error_cnt + 1;
            end

            if (dut.ram_dina !== exp_data) begin
                error_cnt = error_cnt + 1;
            end

            write_cnt = write_cnt + 1;
        end
    end

    initial begin
        rst_n     = 1'b0;
        uart_rx   = 1'b1;
        key0      = 1'b1;
        key1      = 1'b1;
        adc_dout  = 1'b0;
        write_cnt = 0;
        tx_cnt    = 0;
        error_cnt = 0;
        adc_sample_idx = 0;
        adc_bit_sel = 0;
        adc_model_data = adc_raw_sample(0);

        repeat (10) @(posedge clk);
        rst_n = 1'b1;
        repeat (10) @(posedge clk);

        send_uart_byte(8'hff);
        send_uart_byte(8'ha0);
        send_uart_byte(8'h00);
        send_uart_byte(8'hff);

        wait (dut.sampling == 1'b1);
        wait (write_cnt == CHECK_NUM);
        wait (dut.sampling == 1'b0);
        repeat (20) @(posedge clk);

        if (write_cnt !== CHECK_NUM) begin
            error_cnt = error_cnt + 1;
        end

        press_key1();

        for (i = 0; i < CHECK_NUM; i = i + 1) begin
            exp_data = adc_to_voltage(adc_raw_sample(i));

            recv_uart_byte(rx_byte);
            tx_cnt = tx_cnt + 1;
            if (rx_byte !== exp_data[7:0]) begin
                error_cnt = error_cnt + 1;
            end

            recv_uart_byte(rx_byte);
            tx_cnt = tx_cnt + 1;
            if (rx_byte !== exp_data[15:8]) begin
                error_cnt = error_cnt + 1;
            end
        end

        if (tx_cnt !== UART_BYTES) begin
            error_cnt = error_cnt + 1;
        end

        $finish;
    end

endmodule
  
