`timescale 1ns / 1ps

module total_tb;

    localparam integer CLK_PERIOD = 20;   // 50 MHz
    localparam integer CHECK_NUM  = 256;
    localparam integer BAUD_CLKS  = 5208; // 50 MHz / 9600 baud

    reg clk;
    reg rst_n;
    reg uart_rx;
    reg key0;
    reg key1;
    reg adc_dout;

    wire adc_cs;
    wire adc_sclk;
    wire adc_din;
    wire uart_tx;

    integer i;
    integer write_cnt;
    integer error_cnt;
    reg [15:0] exp_data;

    total dut (
        .clk      (clk),
        .rst_n    (rst_n),
        .uart_rx  (uart_rx),
        .key0     (key0),
        .key1     (key1),
        .adc_dout (adc_dout),
        .adc_cs   (adc_cs),
        .adc_sclk (adc_sclk),
        .adc_din  (adc_din),
        .uart_tx  (uart_tx)
    );

    initial begin
        clk = 1'b0;
        forever #(CLK_PERIOD / 2) clk = ~clk;
    end

    task send_uart_byte;
        input [7:0] data;
        integer bit_idx;
        begin
            uart_rx = 1'b0;
            repeat (BAUD_CLKS) @(posedge clk);

            for (bit_idx = 0; bit_idx < 8; bit_idx = bit_idx + 1) begin
                uart_rx = data[bit_idx];
                repeat (BAUD_CLKS) @(posedge clk);
            end

            uart_rx = 1'b1;
            repeat (BAUD_CLKS) @(posedge clk);
        end
    endtask

    // Count and check every RAM write generated by total.v.
    always @(posedge clk) begin
        if (rst_n && dut.ena && dut.wea) begin
            exp_data = 16'h1000 + write_cnt[15:0];

            if (dut.addra !== write_cnt[7:0]) begin
                $display("[%0t] ERROR: write %0d address mismatch, expect %0d, got %0d",
                         $time, write_cnt, write_cnt[7:0], dut.addra);
                error_cnt = error_cnt + 1;
            end

            if (dut.ram_dina !== exp_data) begin
                $display("[%0t] ERROR: write %0d data mismatch, expect 0x%04h, got 0x%04h",
                         $time, write_cnt, exp_data, dut.ram_dina);
                error_cnt = error_cnt + 1;
            end

            write_cnt = write_cnt + 1;
        end
    end

    initial begin
        rst_n     = 1'b0;
        uart_rx   = 1'b1;
        key0      = 1'b1;
        key1      = 1'b1;
        adc_dout  = 1'b0;
        write_cnt = 0;
        error_cnt = 0;

        force dut.adc_change_done = 1'b0;
        force dut.adc_data = 16'd0;

        repeat (10) @(posedge clk);
        rst_n = 1'b1;
        repeat (10) @(posedge clk);

        send_uart_byte(8'hff);
        send_uart_byte(8'ha0);
        send_uart_byte(8'h00);
        send_uart_byte(8'hff);

        wait (dut.sampling == 1'b1);
        repeat (2) @(posedge clk);

        for (i = 0; i < CHECK_NUM; i = i + 1) begin
            force dut.adc_data = 16'h1000 + i[15:0];
            force dut.adc_change_done = 1'b1;
            @(posedge clk);
            force dut.adc_change_done = 1'b0;
            @(posedge clk);
        end

        repeat (10) @(posedge clk);

        if (write_cnt !== CHECK_NUM) begin
            $display("ERROR: expected %0d RAM writes, got %0d", CHECK_NUM, write_cnt);
            error_cnt = error_cnt + 1;
        end

        if (error_cnt == 0) begin
            $display("PASS: checked %0d data writes successfully.", CHECK_NUM);
        end else begin
            $display("FAIL: checked %0d data writes, error_cnt = %0d.", CHECK_NUM, error_cnt);
        end

        release dut.adc_change_done;
        release dut.adc_data;

        $finish;
    end

endmodule

// Define TOTAL_TB_BEHAVIORAL_IP when running without Vivado-generated IP
// simulation models.
`ifdef TOTAL_TB_BEHAVIORAL_IP
module ram_16_256 (
    input  wire        clka,
    input  wire        ena,
    input  wire        wea,
    input  wire [7:0]  addra,
    input  wire [15:0] dina,
    input  wire        clkb,
    input  wire        enb,
    input  wire [7:0]  addrb,
    output reg  [15:0] doutb
);
    reg [15:0] mem [0:255];

    always @(posedge clka) begin
        if (ena && wea)
            mem[addra] <= dina;
    end

    always @(posedge clkb) begin
        if (enb)
            doutb <= mem[addrb];
    end
endmodule

module fifo_ram_to_uart (
    input  wire        rst,
    input  wire        wr_clk,
    input  wire        rd_clk,
    input  wire [15:0] din,
    input  wire        wr_en,
    input  wire        rd_en,
    output reg  [7:0]  dout,
    output wire        full,
    output wire        almost_full,
    output wire        empty,
    output wire        almost_empty,
    output wire [9:0]  rd_data_count,
    output wire [8:0]  wr_data_count,
    output wire        wr_rst_busy,
    output wire        rd_rst_busy
);
    reg [7:0] mem [0:511];
    reg [8:0] wr_ptr;
    reg [8:0] rd_ptr;
    reg [9:0] count;

    assign empty         = (count == 0);
    assign almost_empty  = (count <= 1);
    assign full          = (count >= 512);
    assign almost_full   = (count >= 510);
    assign rd_data_count = count;
    assign wr_data_count = count[8:0];
    assign wr_rst_busy   = 1'b0;
    assign rd_rst_busy   = 1'b0;

    always @(posedge wr_clk or posedge rst) begin
        if (rst) begin
            wr_ptr <= 9'd0;
        end else if (wr_en && !full) begin
            mem[wr_ptr]     <= din[7:0];
            mem[wr_ptr + 1] <= din[15:8];
            wr_ptr          <= wr_ptr + 2'd2;
        end
    end

    always @(posedge rd_clk or posedge rst) begin
        if (rst) begin
            rd_ptr <= 9'd0;
            dout   <= 8'd0;
            count  <= 10'd0;
        end else begin
            if (wr_en && !full && !(rd_en && !empty))
                count <= count + 2'd2;
            else if (rd_en && !empty && !(wr_en && !full))
                count <= count - 1'b1;

            if (rd_en && !empty) begin
                dout   <= mem[rd_ptr];
                rd_ptr <= rd_ptr + 1'b1;
            end
        end
    end
endmodule
`endif
  
